#!/bin/bash
set -euo pipefail

trap 'echo "[run_tts_server] shutting down"; kill -- -$$ >/dev/null 2>&1 || true' EXIT INT TERM

export PYTHONPATH="/workspace/vllm-omni:${PYTHONPATH:-}"

GPU_MIN_FREE_MIB=${GPU_MIN_FREE_MIB:-8000}
if command -v nvidia-smi >/dev/null 2>&1; then
  FREE_MEM=$(nvidia-smi --query-gpu=memory.free --format=csv,noheader,nounits | head -n1 | tr -d " ")
  if [ -n "$FREE_MEM" ] && [ "$FREE_MEM" -lt "$GPU_MIN_FREE_MIB" ]; then
    echo "[run_tts_server] GPU free ${FREE_MEM} MiB < ${GPU_MIN_FREE_MIB} MiB; aborting start"
    exit 1
  fi
fi

# ====== 黄金基线配置 (20260208_200725, CP+Decoder CUDA Graph) ======
# 模型：0.6B（不是 1.7B！）
TTS_MODEL_DIR=${TTS_MODEL_DIR:-/workspace/models/Qwen3-TTS-12Hz-0.6B-CustomVoice}
TTS_STAGE_CONFIG=${TTS_STAGE_CONFIG:-/workspace/project 1/25/artifacts/qwen3_tts_l40s.yaml}
TTS_HOST=${TTS_HOST:-0.0.0.0}
TTS_PORT=${TTS_PORT:-9000}

# 深度流式
TTS_DEEP_STREAM_ENABLE=${TTS_DEEP_STREAM_ENABLE:-1}
TTS_DEEP_STREAM_PROCESS=${TTS_DEEP_STREAM_PROCESS:-0}
TTS_DEEP_STREAM_CODEGEN_BLOCKING=${TTS_DEEP_STREAM_CODEGEN_BLOCKING:-0}
TTS_DEEP_STREAM_SYNC_MODE=${TTS_DEEP_STREAM_SYNC_MODE:-phase}
TTS_DEEP_STREAM_INCREMENTAL=${TTS_DEEP_STREAM_INCREMENTAL:-1}
TTS_DEEP_STREAM_PACKET_TOKENS=${TTS_DEEP_STREAM_PACKET_TOKENS:-2}
TTS_DEEP_STREAM_PACKET_SCHEDULE=${TTS_DEEP_STREAM_PACKET_SCHEDULE:-fixed2}
TTS_DEEP_STREAM_LEFT_CONTEXT=${TTS_DEEP_STREAM_LEFT_CONTEXT:-72}
TTS_DEEP_STREAM_DEVICE=${TTS_DEEP_STREAM_DEVICE:-cuda:0}
TTS_DEEP_STREAM_CODEGEN_DEVICE=${TTS_DEEP_STREAM_CODEGEN_DEVICE:-cuda:0}

# 确定性
TTS_DEEP_STREAM_DETERMINISTIC=${TTS_DEEP_STREAM_DETERMINISTIC:-1}
TTS_DEEP_STREAM_DETERMINISTIC_POLICY=${TTS_DEEP_STREAM_DETERMINISTIC_POLICY:-greedy}
TTS_DEEP_STREAM_SEED_MODE=${TTS_DEEP_STREAM_SEED_MODE:-fixed}
TTS_DEEP_STREAM_SEED=${TTS_DEEP_STREAM_SEED:-42}

# CUDA Graph 加速（RFA 验收 20260208 全 PASS）
TTS_CODEGEN_CUDAGRAPH_CP=${TTS_CODEGEN_CUDAGRAPH_CP:-1}         # CP Graph：codegen RTF 0.89→0.45, bit-exact
TTS_CODEGEN_CUDAGRAPH_TALKER=${TTS_CODEGEN_CUDAGRAPH_TALKER:-0} # Talker Graph：不 bit-exact，保持关闭
TTS_DECODER_CUDAGRAPH=${TTS_DECODER_CUDAGRAPH:-1}               # Decoder Graph：e2e RTF ~0.70
TTS_CODEGEN_GROUP_PARALLEL=${TTS_CODEGEN_GROUP_PARALLEL:-0}      # 禁止 auto，会毁音质

# 调试（默认关闭避免性能干扰）
TTS_DEEP_STREAM_PACKET_TRACE=${TTS_DEEP_STREAM_PACKET_TRACE:-0}
TTS_DEEP_STREAM_METRICS=${TTS_DEEP_STREAM_METRICS:-0}
TTS_CODE_DUMP_ENABLE=${TTS_CODE_DUMP_ENABLE:-0}
TTS_CODE_DUMP_DIR=${TTS_CODE_DUMP_DIR:-/workspace/project 1/25/output/code_dumps}

export TTS_MODEL_DIR TTS_STAGE_CONFIG TTS_HOST TTS_PORT
export TTS_DEEP_STREAM_ENABLE TTS_DEEP_STREAM_PROCESS TTS_DEEP_STREAM_CODEGEN_BLOCKING
export TTS_DEEP_STREAM_SYNC_MODE TTS_DEEP_STREAM_INCREMENTAL
export TTS_DEEP_STREAM_PACKET_TOKENS TTS_DEEP_STREAM_PACKET_SCHEDULE TTS_DEEP_STREAM_LEFT_CONTEXT
export TTS_DEEP_STREAM_DEVICE TTS_DEEP_STREAM_CODEGEN_DEVICE
export TTS_DEEP_STREAM_DETERMINISTIC TTS_DEEP_STREAM_DETERMINISTIC_POLICY
export TTS_DEEP_STREAM_SEED_MODE TTS_DEEP_STREAM_SEED
export TTS_CODEGEN_CUDAGRAPH_CP TTS_CODEGEN_CUDAGRAPH_TALKER TTS_DECODER_CUDAGRAPH TTS_CODEGEN_GROUP_PARALLEL
export TTS_DEEP_STREAM_PACKET_TRACE TTS_DEEP_STREAM_METRICS
export TTS_CODE_DUMP_ENABLE TTS_CODE_DUMP_DIR

echo "[run_tts_server] MODEL=$TTS_MODEL_DIR POLICY=$TTS_DEEP_STREAM_DETERMINISTIC_POLICY PACKETS=$TTS_DEEP_STREAM_PACKET_TOKENS LEFT=$TTS_DEEP_STREAM_LEFT_CONTEXT CP_GRAPH=$TTS_CODEGEN_CUDAGRAPH_CP DEC_GRAPH=$TTS_DECODER_CUDAGRAPH GP=$TTS_CODEGEN_GROUP_PARALLEL"
python3 "/workspace/project 1/25/clients/tts_server.py"
